// Bilingual dictionary (FR-37). Per-user language preference with RTL for Arabic.
export type Lang = 'en' | 'ar';

const dict = {
  appTitle: ['AIC Time & Attendance', 'نظام الحضور والانصراف — العافية'],
  appSubtitle: ['Savola Foods — Afia International Company, Jeddah (Prototype)', 'صافولا للأغذية — شركة عافية العالمية، جدة (نموذج أولي)'],
  dashboard: ['Dashboard', 'لوحة المعلومات'],
  attendance: ['FTE Attendance', 'حضور الموظفين'],
  casuals: ['Casual Workforce', 'العمالة المؤقتة'],
  access: ['Gate Access', 'بوابات الدخول'],
  reports: ['Reports', 'التقارير'],
  admin: ['Admin', 'الإعدادات'],
  period: ['Period: June 2026', 'الفترة: يونيو 2026'],
  onSiteNow: ['On site now', 'المتواجدون حالياً'],
  clockCompliance: ['Clock-in compliance', 'نسبة الالتزام بالبصمة'],
  openExceptions: ['Open exceptions', 'الحالات المفتوحة'],
  otHoursMtd: ['OT hours (month)', 'ساعات العمل الإضافي (الشهر)'],
  topPunctualDepts: ['Top punctual departments', 'أكثر الإدارات التزاماً'],
  topLateDepts: ['Departments by late-ins', 'الإدارات حسب التأخير'],
  topOtEmployees: ['Top employees by OT', 'الأعلى في العمل الإضافي'],
  topAbsence: ['Top absence days', 'الأعلى غياباً'],
  empNo: ['Emp No.', 'الرقم الوظيفي'],
  empName: ['Emp Name', 'اسم الموظف'],
  lineManager: ['Line Manager', 'المدير المباشر'],
  date: ['Date', 'التاريخ'],
  in: ['In', 'دخول'],
  out: ['Out', 'خروج'],
  shiftName: ['Shift Name', 'اسم الوردية'],
  shiftIn: ['Shift In', 'بداية الوردية'],
  shiftOut: ['Shift Out', 'نهاية الوردية'],
  shortageHours: ['Shortage Hours', 'ساعات النقص'],
  lateIn: ['Late In', 'تأخير الحضور'],
  earlyOut: ['Early Out', 'خروج مبكر'],
  otNormal: ['OT Normal', 'إضافي عادي'],
  otHoliday: ['OT Holiday', 'إضافي عطلة'],
  totalHours: ['Total Hours', 'إجمالي الساعات'],
  completionPct: ['Required Hrs Completion %', 'نسبة إكمال الساعات المطلوبة'],
  dept: ['Department', 'الإدارة'],
  allDepts: ['All departments', 'كل الإدارات'],
  allManagers: ['All managers', 'كل المدراء'],
  exceptionsOnly: ['Exceptions only', 'الحالات فقط'],
  all: ['All', 'الكل'],
  missingPunch: ['Missing punch', 'بصمة مفقودة'],
  missingIn: ['Missing In', 'بصمة دخول مفقودة'],
  missingOut: ['Missing Out', 'بصمة خروج مفقودة'],
  editReason: ['Edit Reason', 'سبب التعديل'],
  manualIn: ['Manual In', 'دخول يدوي'],
  manualOut: ['Manual Out', 'خروج يدوي'],
  manualBoth: ['Manual In+Out', 'دخول وخروج يدوي'],
  dayOffsPanel: ['Team day offs', 'أيام راحة الفريق'],
  addDayOffBtn: ['Add day off', 'إضافة يوم راحة'],
  dayOffNote: ['Working a granted day off or a public holiday counts as full-day OT, exempt from the daily OT cap.', 'العمل في يوم راحة ممنوح أو عطلة رسمية يُحتسب عملاً إضافياً ليوم كامل دون سقف يومي.'],
  delegateSupervisor: ['Delegate supervisor', 'تفويض مشرف'],
  noneOption: ['None', 'بدون'],
  pendingApprovals: ['Supervisor changes pending approval', 'تغييرات المشرف بانتظار الاعتماد'],
  approveSelected: ['Approve selected', 'اعتماد المحدد'],
  rejectSelected: ['Reject selected', 'رفض المحدد'],
  selectAll: ['Select all', 'تحديد الكل'],
  noPending: ['No pending changes.', 'لا توجد تغييرات معلقة.'],
  sentForApproval: ['Sent to the manager for approval.', 'أُرسل إلى المدير للاعتماد.'],
  supervisorRole: ['Supervisor', 'مشرف'],
  supervisorRoleDesc: ['Delegated by a line manager: submit punch corrections and day offs for the team — every change requires manager approval.', 'مفوض من المدير المباشر: تقديم تصحيحات البصمات وأيام الراحة للفريق — كل تغيير يتطلب اعتماد المدير.'],
  noSupervisor: ['No supervisor delegated yet. A line manager can delegate one from the My Team screen.', 'لم يتم تفويض مشرف بعد. يمكن للمدير المباشر تفويض مشرف من شاشة فريقي.'],
  selectSupervisor: ['Sign in as supervisor', 'الدخول بصفة مشرف'],
  hrAlerts: ['HR alerts', 'تنبيهات الموارد البشرية'],
  alertsPanel: ['Suspicious activity — authority misuse monitor', 'النشاط المشبوه — مراقبة إساءة استخدام الصلاحيات'],
  alertsNote: ['Non-blocking: changes stay applied and audited — HR is informed to review. Attribution follows the original author (supervisor changes stay attributed to the supervisor even after manager approval).', 'غير مانع: تبقى التغييرات مطبقة ومسجلة — يتم إبلاغ الموارد البشرية للمراجعة. تُنسب التغييرات لصاحبها الأصلي (تغييرات المشرف تبقى منسوبة له حتى بعد اعتماد المدير).'],
  noAlerts: ['No suspicious activity detected.', 'لم يُرصد أي نشاط مشبوه.'],
  kindBigShift: ['Large punch time change', 'تغيير كبير في وقت البصمة'],
  kindOtConc: ['Repeated manual OT for the same employee', 'إضافي يدوي متكرر لنفس الموظف'],
  kindVolume: ['Unusually many manual edits', 'عدد كبير من التعديلات اليدوية'],
  kindDayoffOt: ['Day off granted on a day already worked → full-day OT', 'منح يوم راحة عن يوم تم العمل فيه ← إضافي يوم كامل'],
  sevHigh: ['High', 'مرتفع'],
  sevMedium: ['Medium', 'متوسط'],
  severity: ['Severity', 'الخطورة'],
  times: ['times', 'مرة'],
  edits: ['edits', 'تعديل'],
  originalTimes: ['Original', 'التوقيت الأصلي'],
  resetTimes: ['↺ Reset to original', '↺ استعادة الأصلي'],
  pickTime: ['Pick time from clock', 'اختيار الوقت من الساعة'],
  invalidTime: ['Incomplete time — pick from the clock or complete the HH:MM value. The window cannot be closed while a time is invalid.', 'وقت غير مكتمل — اختر من الساعة أو أكمل الصيغة HH:MM. لا يمكن إغلاق النافذة والوقت غير صحيح.'],
  late: ['Late', 'متأخر'],
  absent: ['Absent', 'غائب'],
  rest: ['Rest day', 'يوم راحة'],
  leave: ['Leave', 'إجازة'],
  dayOff: ['Day-off (paid)', 'يوم راحة (مدفوع)'],
  holidayWorked: ['Holiday worked', 'عمل في عطلة'],
  notEmployed: ['Not employed', 'خارج الخدمة'],
  worked: ['Worked', 'حضور'],
  edit: ['Edit', 'تعديل'],
  editPunch: ['Correct punches', 'تصحيح البصمات'],
  reason: ['Reason (required)', 'السبب (إلزامي)'],
  save: ['Save', 'حفظ'],
  cancel: ['Cancel', 'إلغاء'],
  iqama: ['Iqama No.', 'رقم الإقامة'],
  supplier: ['Supplier', 'المورد'],
  supervisor: ['Supervisor', 'المشرف'],
  religion: ['Religion', 'الديانة'],
  muslim: ['Muslim', 'مسلم'],
  nonMuslim: ['Non-Muslim', 'غير مسلم'],
  jobTitle: ['Job Title', 'المسمى الوظيفي'],
  monthlySalary: ['Monthly Salary', 'الراتب الشهري'],
  healthCard: ['Health Card', 'الشهادة الصحية'],
  ajeer: ['Ajeer', 'أجير'],
  active: ['Active', 'نشط'],
  inactive: ['Inactive', 'غير نشط'],
  incentive: ['Incentive', 'الحافز'],
  violations: ['Violations', 'المخالفات'],
  deduction: ['Deduction', 'الخصم'],
  totalSalary: ['Total Salary', 'إجمالي الراتب'],
  attendancePay: ['Attendance Pay', 'أجر الحضور'],
  daysWorked: ['Days worked', 'أيام العمل'],
  timesheet: ['Timesheet', 'كشف الدوام'],
  calculatedDailySalary: ['Calculated Daily Salary', 'الأجر اليومي المحسوب'],
  ot: ['OT', 'إضافي'],
  gateSimulator: ['Gate scan simulator', 'محاكاة بوابة الدخول'],
  scan: ['Scan', 'مسح'],
  green: ['GREEN — access granted', 'أخضر — مسموح بالدخول'],
  red: ['RED — access denied', 'أحمر — ممنوع من الدخول'],
  terminated: ['Terminated', 'منتهي الخدمة'],
  hcExpired: ['Health Card expired', 'الشهادة الصحية منتهية'],
  ajeerExpired: ['Ajeer expired', 'أجير منتهي'],
  notYetHired: ['Not yet hired', 'لم يباشر بعد'],
  expiryAlerts: ['Compliance alerts (60-day window)', 'تنبيهات الامتثال (60 يوماً)'],
  expiresOn: ['Expires', 'ينتهي في'],
  fteDetailed: ['FTE Detailed (FR-39)', 'تفصيلي للموظفين (FR-39)'],
  fteSummary: ['FTE Period Summary (FR-40)', 'ملخص الفترة للموظفين (FR-40)'],
  casualTimesheet: ['Casual Timesheet (FR-42)', 'كشف دوام العمالة (FR-42)'],
  casualSummary: ['Casual Period Summary (FR-42)', 'ملخص العمالة المؤقتة (FR-42)'],
  canteenReport: ['Canteen (FR-41)', 'المقصف (FR-41)'],
  nightAllowance: ['Night Allowance (FR-19)', 'بدل الوردية الليلية (FR-19)'],
  totalShortage: ['Total Shortage', 'إجمالي النقص'],
  totalLateIn: ['Total Late In', 'إجمالي التأخير'],
  totalEarlyOut: ['Total Early Out', 'إجمالي الخروج المبكر'],
  totalOtNormal: ['Total OT Normal', 'إجمالي الإضافي العادي'],
  totalOtHoliday: ['Total OT Holiday', 'إجمالي إضافي العطل'],
  eligibleDays: ['Eligible night days', 'أيام الوردية الليلية'],
  amountSar: ['Amount (SAR)', 'المبلغ (ريال)'],
  device1Days: ['Canteen 1 | 5 SAR (Day)', 'مقصف 1 | 5 ريال (يوم)'],
  device2Days: ['Canteen 2 | 15 SAR (Day)', 'مقصف 2 | 15 ريال (يوم)'],
  exportCsv: ['Export CSV', 'تصدير CSV'],
  ramadanWindow: ['Ramadan window (simulation)', 'فترة رمضان (محاكاة)'],
  ramadanOff: ['No Ramadan window set. Set one to see IR/CR shifts, 6h Muslim days and Ramadan pay rules recompute live.', 'لم يتم تحديد فترة رمضان. حددها لمشاهدة ورديات رمضان وإعادة الاحتساب مباشرة.'],
  from: ['From', 'من'],
  to: ['To', 'إلى'],
  apply: ['Apply', 'تطبيق'],
  clear: ['Clear', 'مسح'],
  holidays: ['Public holidays (BR-09)', 'العطل الرسمية (BR-09)'],
  addHoliday: ['Add holiday', 'إضافة عطلة'],
  devices: ['Device estate (§7.2)', 'الأجهزة (§7.2)'],
  online: ['Online', 'متصل'],
  offline: ['Offline', 'غير متصل'],
  auditTrail: ['Audit trail (FR-38)', 'سجل التدقيق (FR-38)'],
  noAudit: ['No edits yet. Corrections made in the attendance screens appear here with before/after values.', 'لا توجد تعديلات بعد. ستظهر التصحيحات هنا مع القيم قبل وبعد التعديل.'],
  policyParams: ['Policy parameters', 'إعدادات السياسات'],
  shiftsPanel: ['Shift catalogue (FR-07/08/11)', 'دليل الورديات (FR-07/08/11)'],
  shiftsNote: ['Shift changes recompute all attendance instantly; demo punches regenerate from the active catalogue. The last shift of a category cannot be deleted.', 'أي تعديل على الورديات يعيد احتساب الحضور فوراً وتُولَّد بصمات العرض من الدليل النشط. لا يمكن حذف آخر وردية في فئتها.'],
  code: ['Code', 'الرمز'],
  field: ['Field', 'ميداني'],
  ramadanTag: ['Ramadan', 'رمضان'],
  requiredH: ['Required (h)', 'المطلوب (ساعات)'],
  addShift: ['Add shift', 'إضافة وردية'],
  updateShift: ['Update shift', 'تحديث الوردية'],
  deleteBtn: ['Delete', 'حذف'],
  codeExists: ['A shift with this code already exists.', 'يوجد وردية بهذا الرمز مسبقاً.'],
  confirmDeleteShift: ['Delete this shift? Attendance will be recomputed.', 'هل تريد حذف هذه الوردية؟ سيعاد احتساب الحضور.'],
  gracePeriod: ['Grace period (min)', 'فترة السماح (دقيقة)'],
  otCap: ['Daily OT cap (min)', 'سقف الإضافي اليومي (دقيقة)'],
  status: ['Status', 'الحالة'],
  employee: ['Employee', 'موظف'],
  casual: ['Casual', 'عامل مؤقت'],
  fte: ['FTE', 'موظف'],
  segment: ['Segment', 'الفئة'],
  office: ['Office', 'مكتبي'],
  shiftWorker: ['Shift', 'ورديات'],
  manager: ['Manager', 'مدير'],
  searchName: ['Search name / number…', 'ابحث بالاسم أو الرقم…'],
  showingDays: ['days shown', 'يوم معروض'],
  uncountedNote: ['* OT beyond the 4h daily cap is stored as uncounted extra hours (FR-16).', '* الساعات فوق سقف 4 ساعات تُسجل كساعات غير محتسبة (FR-16).'],
  langBtn: ['العربية', 'English'],
  mergeReports: ['Report Merge', 'دمج التقارير'],
  mergeIntro: ['Upload the four period exports — TAS (HR Works), Car Gate (Speca), Leaves and Active list (Oracle Fusion). Files are auto-detected; everything runs in your browser and nothing is uploaded to a server.', 'ارفع تقارير الفترة الأربعة — نظام الحضور TAS، بوابة السيارات، الإجازات وقائمة الموظفين النشطين. يتم التعرف على الملفات تلقائياً وتتم المعالجة في متصفحك دون رفع لأي خادم.'],
  mergeDrop: ['Drop the .xlsx files here, or click to choose', 'أسقط ملفات .xlsx هنا أو انقر للاختيار'],
  mergeDropHint: ['You can drop all four at once — each report is recognized automatically.', 'يمكن إسقاط الملفات الأربعة دفعة واحدة — يتم التعرف على كل تقرير تلقائياً.'],
  mergeUnknownFile: ['not recognized as TAS / Car Gate / Leaves / Active list', 'لم يتم التعرف عليه كأحد التقارير الأربعة'],
  mergeReadError: ['could not read this file', 'تعذر قراءة الملف'],
  mergeReading: ['Reading files…', 'جارٍ قراءة الملفات…'],
  mergeWorking: ['Merging…', 'جارٍ الدمج…'],
  mergeWriting: ['Preparing Excel file…', 'جارٍ تجهيز ملف الإكسل…'],
  mergeGenerate: ['Generate merged report', 'إنشاء التقرير المدمج'],
  mergeDownload: ['Download Merged_Attendance.xlsx', 'تنزيل التقرير المدمج xlsx'],
  mergeNeed: ['TAS and Active list are required; Car Gate and Leaves are optional.', 'ملف TAS وقائمة النشطين مطلوبان؛ بوابة السيارات والإجازات اختياريان.'],
  mergeEmployees: ['Employees', 'الموظفون'],
  mergeRows: ['Attendance rows', 'صفوف الحضور'],
  mergePunchesImproved: ['Punches improved by gate', 'بصمات حسّنتها البوابة'],
  mergeStatusUpgraded: ['Absences resolved by gate', 'غيابات صححتها البوابة'],
  mergeLeaveDays: ['Leave days applied', 'أيام إجازة مطبقة'],
  mergeUnmatchedGate: ['Unmatched gate names', 'أسماء بوابة غير مطابقة'],
  mergeUnresolvedLeaves: ['Approved leaves not applied (with reason)', 'إجازات معتمدة لم تُطبق (مع السبب)'],
  mergeEvents: ['Events', 'أحداث'],
  mergeReason: ['Reason', 'السبب'],
  mergeLeaveType: ['Leave Type', 'نوع الإجازة'],
  mergeGateNote: ['Mostly trainees/visitors or spellings the matcher could not resolve safely. Ask Speca to add the employee number to the report for 100% coverage.', 'غالبها متدربون/زوار أو أسماء تعذر تحديدها بأمان. أضِف الرقم الوظيفي لتقرير البوابة لتغطية كاملة.'],
  mergePreview: ['Preview — first 40 rows', 'معاينة — أول 40 صفاً'],
  mergePreviewNote: ['The downloaded file contains all rows plus a Summary & Exceptions sheet. Yellow = time taken from the Car Gate; green = leave applied.', 'الملف المنزّل يحتوي جميع الصفوف مع ورقة ملخص واستثناءات. الأصفر = وقت من بوابة السيارات؛ الأخضر = إجازة مطبقة.'],
  kpiVsTarget: ['target ≥ 95%', 'المستهدف ≥ 95%'],
  correctionsNote: ['Every correction requires a reason and is audit-trailed (FR-33/38).', 'كل تصحيح يتطلب سبباً ويُسجل في سجل التدقيق (FR-33/38).'],
  night: ['Night', 'ليلي'],
  days: ['days', 'يوم'],
  hours: ['h', 'س'],
  sar: ['SAR', 'ريال'],
  gateEventsToday: ['Latest gate decisions (simulated today = 2026-06-30)', 'أحدث قرارات البوابة (اليوم الافتراضي 2026-06-30)'],
  before: ['Before', 'قبل'],
  after: ['After', 'بعد'],
  by: ['By', 'بواسطة'],
  at: ['At', 'في'],
  what: ['Change', 'التغيير'],
  landingWelcome: ['Welcome — sign in to continue', 'مرحباً — سجّل الدخول للمتابعة'],
  landingHint: ['Prototype: choose a role to see the portal each persona gets (NFR-07 role-based access).', 'نموذج أولي: اختر دوراً لعرض البوابة المخصصة لكل مستخدم (صلاحيات حسب الدور NFR-07).'],
  hrRole: ['HR Operations', 'عمليات الموارد البشرية'],
  hrRoleDesc: ['Full console: all employees & casuals, gate validation, policy configuration, reports and audit trail.', 'وصول كامل: جميع الموظفين والعمالة المؤقتة، بوابات الدخول، إعدادات السياسات، التقارير وسجل التدقيق.'],
  managerRole: ['Line Manager', 'مدير مباشر'],
  managerRoleDesc: ['My team only: daily corrections, exceptions, day-offs and team reports (FR-33).', 'فريقي فقط: التصحيحات اليومية، الحالات، أيام الراحة وتقارير الفريق (FR-33).'],
  selectManager: ['Sign in as', 'الدخول بصفة'],
  continueBtn: ['Enter portal', 'دخول البوابة'],
  switchRole: ['Switch role', 'تغيير الدور'],
  myTeam: ['My Team', 'فريقي'],
  teamMembers: ['direct reports', 'موظف تابع'],
  signedInAs: ['Signed in as', 'مسجل الدخول بصفة'],
  manualTag: ['Manual', 'يدوي'],
  modRequest: ['Modification Request', 'طلب تعديل'],
  modRequestDesc: ['Describe the change or issue. It is filed directly to the development backlog and reviewed before every release.', 'صف التعديل أو الملاحظة. يُرسل الطلب مباشرة إلى قائمة التطوير ويُراجع قبل كل إصدار.'],
  yourName: ['Your name', 'اسمك'],
  screenField: ['Screen', 'الشاشة'],
  commentsField: ['Comments / requested change', 'الملاحظات / التعديل المطلوب'],
  sendRequest: ['Send request', 'إرسال الطلب'],
  sending: ['Sending…', 'جارٍ الإرسال…'],
  sentOk: ['Request submitted — tracking no.', 'تم إرسال الطلب — رقم المتابعة'],
  sendFailed: ['Could not submit. If you are running locally, requests only work on the deployed site.', 'تعذر الإرسال. الطلبات تعمل فقط على النسخة المنشورة.'],
  commentTooShort: ['Please describe the request (at least a sentence).', 'يرجى وصف الطلب (جملة واحدة على الأقل).'],
  close: ['Close', 'إغلاق'],
  manualNote: ['✎ = manually corrected punch (who/when/why in the audit trail, FR-38).', '✎ = بصمة مصححة يدوياً (التفاصيل في سجل التدقيق FR-38).'],
} as const;

export type TKey = keyof typeof dict;
export const t = (key: TKey, lang: Lang): string => dict[key][lang === 'en' ? 0 : 1];
